require("setup/theme")
-- neodev must come before the LSP configuration
require("setup/neodev")
require("setup/mason-lsp")
require("setup/rust-tools")
require("setup/python-lsps")
require("setup/python-dap")
require("setup/autopairs")
require("setup/nvim-cmp")
require("setup/telescope")
require("setup/treesitter")
require("setup/dap-config")
require("setup/web-devicons")
require("setup/lualine")
require("setup/toggleterm")
require("setup/nvim-tree")
require("setup/neotest")
require("setup/neoscroll")
