require("setup/gruvbox")
require("setup/mason")
require("setup/neodev")
require("setup/rust-tools")
require("setup/pyright-lsp")
require("setup/autopairs")
require("setup/nvim-cmp")
require("setup/telescope")
require("setup/treesitter")
require("setup/dap-config")

